version: "3.8"

services:
  backend:
    image: ghcr.io/taiwanfrp/backend:latest
    container_name: taiwanfrp-backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - COOKIE_AUTH_NAME=auth
      - COOKIE_AUTH_MAX_AGE=604800
      - COOKIE_AUTH_LOGIN_STATE_NAME=oauth_state
      - COOKIE_AUTH_LOGIN_STATE_MAX_AGE=300
      - COOKIE_2FA_REQUIRED_NAME=2fa_required
      - COOKIE_2FA_MAX_AGE=300
      - COOKIE_HTTPONLY=True
      - COOKIE_MAX_AGE=604800
      - COOKIE_PATH=/
      - COOKIE_SAMESITE=lax
      - COOKIE_SECURE=True
      - SITE_URL=https://demo.taiwanfrp.me