"""replace is_active with status and status_reason in api_keys

Revision ID: 61b97dc324e4
Revises: 62c5c8f566d8
Create Date: 2026-08-22 09:35:19.690469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61b97dc324e4"
down_revision: Union[str, Sequence[str], None] = "62c5c8f566d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "DELETED",
                "EXPIRED",
                "EXPOSED",
                "REVOKED_BY_ADMIN",
                "REVOKED_BY_SYSTEM",
                "REVOKED_BY_OTHER",
                name="apikeystatus",
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "api_keys", sa.Column("status_reason", sa.String(length=255), nullable=True)
    )
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.drop_column("api_keys", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_column("api_keys", "status_reason")
    op.drop_column("api_keys", "status")
    # ### end Alembic commands ###
