"""replace is_active with status and status_reason in api_keys

Revision ID: 61b97dc324e4
Revises: 62c5c8f566d8
Create Date: 2026-08-22 09:35:19.690469

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "61b97dc324e4"
down_revision: str | Sequence[str] | None = "62c5c8f566d8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

api_key_status_enum = sa.Enum(
    "active",
    "deleted",
    "expired",
    "exposed",
    "revoked_admin",
    "revoked_system",
    "revoked_other",
    name="apikeystatus",
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        postgresql.ENUM(
            "active",
            "deleted",
            "expired",
            "exposed",
            "revoked_admin",
            "revoked_system",
            "revoked_other",
            name="apikeystatus",
        ).create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "status",
            api_key_status_enum,
            nullable=False,
            server_default="active",
        ),
    )
    op.add_column(
        "api_keys", sa.Column("status_reason", sa.String(length=255), nullable=True)
    )
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.drop_column("api_keys", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_column("api_keys", "status_reason")
    op.drop_column("api_keys", "status")
    # ### end Alembic commands ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        postgresql.ENUM(name="apikeystatus").drop(bind, checkfirst=True)
