"""add token fields to tunnels

Revision ID: 62c5c8f566d8
Revises: 9902c0f1893e
Create Date: 2026-08-12 09:48:19.888217

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62c5c8f566d8"
down_revision: str | Sequence[str] | None = "9902c0f1893e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tunnels", sa.Column("token_prefix", sa.String(length=20), nullable=False)
    )
    op.add_column(
        "tunnels", sa.Column("token_hashed", sa.String(length=64), nullable=False)
    )
    op.create_index(
        op.f("ix_tunnels_token_prefix"), "tunnels", ["token_prefix"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tunnels_token_prefix"), table_name="tunnels")
    op.drop_column("tunnels", "token_hashed")
    op.drop_column("tunnels", "token_prefix")
    # ### end Alembic commands ###
