"""add tunnels table

Revision ID: 70a09e22e6b9
Revises: 1f463d013beb
Create Date: 2026-07-13 12:32:31.980909

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "70a09e22e6b9"
down_revision: Union[str, Sequence[str], None] = "1f463d013beb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tunnels",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("node_id", sa.Integer(), nullable=False),
        sa.Column(
            "protocol",
            sa.Enum(
                "TCP",
                "UDP",
                "HTTP",
                "HTTPS",
                "TCPMUX",
                "STCP",
                "SUDP",
                name="tunnelprotocol",
            ),
            nullable=False,
        ),
        sa.Column("local_ip", sa.String(length=50), nullable=False),
        sa.Column("local_port", sa.Integer(), nullable=False),
        sa.Column("remote_port", sa.Integer(), nullable=True),
        sa.Column("custom_domain", sa.String(length=100), nullable=True),
        sa.Column("is_kcp_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_proxy_protocol_v2_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "DISABLED", name="tunnelstatus"), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("custom_domain"),
    )
    op.create_index(op.f("ix_tunnels_node_id"), "tunnels", ["node_id"], unique=False)
    op.create_index(op.f("ix_tunnels_owner_id"), "tunnels", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tunnels_owner_id"), table_name="tunnels")
    op.drop_index(op.f("ix_tunnels_node_id"), table_name="tunnels")
    op.drop_table("tunnels")
    # ### end Alembic commands ###
