"""add 'is_public' to nodes

Revision ID: 71bd6a179413
Revises: a183c5201fd2
Create Date: 2026-07-06 17:16:31.409833

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "71bd6a179413"
down_revision: str | Sequence[str] | None = "a183c5201fd2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("nodes", sa.Column("is_public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nodes", "is_public")
    # ### end Alembic commands ###
