"""add node table

Revision ID: a183c5201fd2
Revises: bee56b0158bb
Create Date: 2026-07-06 16:37:57.473430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a183c5201fd2'
down_revision: Union[str, Sequence[str], None] = 'bee56b0158bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('port_start', sa.Integer(), nullable=False),
    sa.Column('port_end', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DRAFT', 'REVIEWING', 'MAINTENANCE', 'DISABLED', name='nodestatus'), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_host'), 'nodes', ['host'], unique=True)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=True)
    op.create_index(op.f('ix_nodes_owner_id'), 'nodes', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nodes_owner_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_host'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
